language: objective-c
before_install:
#  - sudo easy_install cpp-coveralls
# sudo: false causes builds to happen in containers rather than VM's
sudo: false
script: 
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme ADALiOS -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme ADALiOS -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -name "*.gcno" -exec cp -v '{}' . \;
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -name "*.gcda" -exec cp -v '{}' . \;
 # - coveralls -e ADALiOS/ADALiOSTests
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme MyTestiOSApp -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
#  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme MyTestiOSApp -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -not -path "*MyTestiOSApp*" -name "*.gcno" -exec cp -v '{}' . \;
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -not -path "*MyTestiOSApp*" -name "*.gcda" -exec cp -v '{}' . \;
  #- coveralls -e ADALiOS/ADALiOSTests

