language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
script: 
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme ADALiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme ADALiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "ADALiOSTests" -name "*.gcno" -exec cp -v '{}' . \;
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "ADALiOSTests" -name "*.gcda" -exec cp -v '{}' . \;
  - coveralls -e ADALiOS/ADALiOSTests

