#dist: trusty
language: objective-c
osx_image: xcode9.4

# set up SonarCube
#addons:
#  sonarcloud:
#    organization: "devex-aad"
#    token:
#      secure: "RXczf7TfFH5rveDaP5iAIet6waDOFO86uTsyM8lmUZrxwHgrwgDChimURPqCeqG9iCNuV+qDO/N7HgI1YJ+s9N2tK/zKOtd1LZFP9c6mVPHOZjY/Sy0DjhOu7XZUex0suqfQDfKJ0wkj+pcMrGfnFAyMtxtow6APk++1Oj1rOAw="
#    github_token:
#      secure: "VtiG/2Yu3I2CVKHdUnmktSd52izbqM1uKxvzNjUc+4lQsRgyMONHO7u21sLI1gnEejyknVkiN9PlprmrK1Apu77S6LocMNYLVd51Vs+38+EVOhc9nt2h9bVy4PEK2ZSaapX5r6/yo3B84qep1KHKanG/Mhwge40E3oiK/cibuVk="
#    branches:
#     - master
#     - dev

#cache:
#   directories:
#      - '$HOME/.sonar/cache'

env:
    matrix:
        - BUILD_TARGETS='ios_framework ios_test_app ios_auto_app' 
        - BUILD_TARGETS='sample_swift_app'
        - BUILD_TARGETS='mac_framework mac_test_app'

# Set up our rubygems (slather and xcpretty, namely)
install: 
 - gem install xcpretty -N
 
before_script:
# Tell the shell to echo failure codes up the pipe so that Travis will properly fail the
# build when the xcodebuild command fails
  - set -o pipefail

script:  
# Run the ADAL build script
  - ./build.py --no-clean --targets $BUILD_TARGETS --show-build-settings
#  - sonar-scanner

after_success:
# Run slather once to have it print out the results in the travis log
#  - slather coverage -s ADAL/ADAL.xcodeproj

after_failure:
  - ./print_logs.sh

notifications:
  slack:
    secure: BIziStN+8QJLjdqNbLyRWWw9kI/MQsX+rZq+xz/bfTANk0gbEryLgMSiEoHxdoctu0dOqOet1voYuDKs3RQW3W0yh0AhDwVgWThNkTA0oDXF8zqm9AXettXNtmYHipaYb6+z6L4lpJOkClQp3hAheu8cM2igqye1O0FQla9g/PA=

